### ISSUE TITLE
Sorry that I closed the issue. This is the first time I've answered an Issue post.Again, which version of ArcGIS are you using? 10.3.0 or 10.3.1?

### ISSUE THREAD

**Issue by lshipman** [Esri/raster2gpkg#3]

**Comment by grl-sage** [comment]
10.3.1

**Comment by lshipman** [comment]
Using 10.3.1 on Windows 7 I'm able to load and display the supplied image. The installation is particularly persnickety so you may want to review the Readme carefully. There are several problems with the loaded image:
1) Is the tiling scheme will be used regardless of the nature of the coordinate reference of the entered image. This may result in less than optimal results or outright failure. Additionally the loaded data draws dark with ArcMap and ArcGIS Pro. The image works will with other apps and with Runtime. We are working on fixes for both of these issues and hope to have a fix shortly.

**Comment by grl-sage** [comment]
Reinstalled from the start.  uninstalled python and reinstalled and then followed the readme.  Tried importing a small PNG to GepPackage and left it to run overnight and it never finished.  I had to kill ArcMap to stop the process from running because cancel would not stop it.

I am going to try an install on a clean machine.

The image I am trying to import is attached if you want to try it.
